App\Entity\Assignation:
    attributes:
        id:
            groups:
                - "assignation:read"
                - "user:read"
                - "chat:read"
                - "assignation:write"
        role:
            groups:
                - "assignation:read"
                - "user:read"
                - "chat:read"
                - "assignation:write"

        permission:
            groups:
                - "assignation:read"
                - "user:read"
                - "chat:read"
                - "assignation:write"
        chat:
            groups:
                - "assignation:read"
                - "user:read"
                - "assignation:write"
        user:
            groups:
                - "assignation:read"
                - "chat:read"
                - "assignation:write"
