App\Entity\User:
    normalizationContext:
        groups:
            - "user:read"
    denormalizationContext:
        groups:
            - "user:write"
    operations:
        ApiPlatform\Metadata\GetCollection:
            filters: ["user.search_filter"]
        ApiPlatform\Metadata\Get: ~
        ApiPlatform\Metadata\Post: ~
        ApiPlatform\Metadata\Put: ~
        ApiPlatform\Metadata\Delete: ~
        ApiPlatform\Metadata\Patch: ~

